package com.sustral.clientapi.controllers;

import com.sustral.clientapi.controllers.types.StandardResponse;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.web.servlet.error.ErrorController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * This controller handles all errors generated by the application.
 *
 * @author Dilanka Dharmasena
 */
@ConditionalOnProperty(name = "deployment.productionMode", havingValue = "true")
@RestController
public class CustomErrorController implements ErrorController {

    private static final String PATH = "/error";

    @RequestMapping(path = PATH)
    public StandardResponse<Void> errorEndpoint() {
        return new StandardResponse<>(null, null);
    }

    @Override
    public String getErrorPath() {
        return PATH;
    }

}
