package com.sustral.clientapi.data.models;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
public class FieldOrganizationRelationshipEntityPK implements Serializable {
    private String fieldId;
    private String organizationId;

    @Column(name = "ffield_id", nullable = false, length = 32)
    @Id
    public String getFieldId() {
        return fieldId;
    }

    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    @Column(name = "organization_id", nullable = false, length = 32)
    @Id
    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FieldOrganizationRelationshipEntityPK that = (FieldOrganizationRelationshipEntityPK) o;

        if (fieldId != null ? !fieldId.equals(that.fieldId) : that.fieldId != null) return false;
        if (organizationId != null ? !organizationId.equals(that.organizationId) : that.organizationId != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = fieldId != null ? fieldId.hashCode() : 0;
        result = 31 * result + (organizationId != null ? organizationId.hashCode() : 0);
        return result;
    }
}
