package com.sustral.clientapi.data.models;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
@Entity
@Table(name = "organizations")
public class OrganizationEntity {
    private String id;
    private String name;
    private Timestamp created;
    private Timestamp updated;

    public OrganizationEntity() {
        // For the JPA
    }

    public OrganizationEntity(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public OrganizationEntity(String id, String name, Timestamp created, Timestamp updated) {
        this.id = id;
        this.name = name;
        this.created = created;
        this.updated = updated;
    }

    @Id
    @Column(name = "id", nullable = false, length = 32)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Basic
    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "created", nullable = false)
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Basic
    @Column(name = "updated", nullable = false)
    public Timestamp getUpdated() {
        return updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        OrganizationEntity that = (OrganizationEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (created != null ? !created.equals(that.created) : that.created != null) return false;
        if (updated != null ? !updated.equals(that.updated) : that.updated != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        result = 31 * result + (updated != null ? updated.hashCode() : 0);
        return result;
    }
}
