package com.sustral.clientapi.data.models;

import com.sustral.clientapi.data.types.ScanStatusE;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
@Entity
@Table(name = "scans")
@IdClass(ScanEntityPK.class)
public class ScanEntity {
    private String id;
    private String fieldId;
    private Timestamp created;
    private Timestamp updated;
    private ScanStatusE scanStatus;

    @Id
    @Column(name = "id", nullable = false, length = 32)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    @Column(name = "ffield_id", nullable = false, length = 32)
    public String getFieldId() {
        return fieldId;
    }

    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    @Basic
    @Column(name = "created", nullable = false)
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Basic
    @Column(name = "updated", nullable = false)
    public Timestamp getUpdated() {
        return updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Basic
    @Enumerated(EnumType.STRING)
    @Column(name = "scan_status", nullable = false)
    public ScanStatusE getScanStatus() {
        return scanStatus;
    }

    public void setScanStatus(ScanStatusE scanStatus) {
        this.scanStatus = scanStatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ScanEntity that = (ScanEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (fieldId != null ? !fieldId.equals(that.fieldId) : that.fieldId != null) return false;
        if (created != null ? !created.equals(that.created) : that.created != null) return false;
        if (updated != null ? !updated.equals(that.updated) : that.updated != null) return false;
        if (scanStatus != null ? !scanStatus.equals(that.scanStatus) : that.scanStatus != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (fieldId != null ? fieldId.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        result = 31 * result + (updated != null ? updated.hashCode() : 0);
        result = 31 * result + (scanStatus != null ? scanStatus.hashCode() : 0);
        return result;
    }
}
