package com.sustral.clientapi.data.models;

import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
@Entity
@Table(name = "sessions")
public class SessionEntity {
    private String token;
    private String userId;
    private Timestamp created;

    public SessionEntity() {
        // For the JPA
    }

    public SessionEntity(String token, String userId) {
        this.token = token;
        this.userId = userId;
    }

    public SessionEntity(String token, String userId, Timestamp created) {
        this.token = token;
        this.userId = userId;
        this.created = created;
    }

    @Id
    @Column(name = "token", nullable = false, length = 64)
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Basic
    @Column(name = "user_id", nullable = false, length = 32)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Basic
    @CreationTimestamp
    @Column(name = "created", nullable = false)
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SessionEntity that = (SessionEntity) o;

        if (token != null ? !token.equals(that.token) : that.token != null) return false;
        if (userId != null ? !userId.equals(that.userId) : that.userId != null) return false;
        if (created != null ? !created.equals(that.created) : that.created != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = token != null ? token.hashCode() : 0;
        result = 31 * result + (userId != null ? userId.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        return result;
    }
}
