package com.sustral.clientapi.data.models;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
public class UserOrganizationRelationshipEntityPK implements Serializable {
    private String userId;
    private String organizationId;

    public UserOrganizationRelationshipEntityPK() {
        // For the JPA
    }

    public UserOrganizationRelationshipEntityPK(String userId, String organizationId) {
        this.userId = userId;
        this.organizationId = organizationId;
    }

    @Column(name = "user_id", nullable = false, length = 32)
    @Id
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "organization_id", nullable = false, length = 32)
    @Id
    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        UserOrganizationRelationshipEntityPK that = (UserOrganizationRelationshipEntityPK) o;

        if (userId != null ? !userId.equals(that.userId) : that.userId != null) return false;
        if (organizationId != null ? !organizationId.equals(that.organizationId) : that.organizationId != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = userId != null ? userId.hashCode() : 0;
        result = 31 * result + (organizationId != null ? organizationId.hashCode() : 0);
        return result;
    }
}
