package com.sustral.clientapi.data.models;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
@Entity
@Table(name = "user_organization_relationships")
@IdClass(UserOrganizationRelationshipEntityPK.class)
public class UserOrganizationRelationshipEntity {
    private String userId;
    private String organizationId;
    private Timestamp created;
    private Timestamp updated;

    public UserOrganizationRelationshipEntity() {
        // For the JPA
    }

    public UserOrganizationRelationshipEntity(String userId, String organizationId) {
        this.userId = userId;
        this.organizationId = organizationId;
    }

    public UserOrganizationRelationshipEntity(String userId, String organizationId, Timestamp created, Timestamp updated) {
        this.userId = userId;
        this.organizationId = organizationId;
        this.created = created;
        this.updated = updated;
    }

    @Id
    @Column(name = "user_id", nullable = false, length = 32)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Id
    @Column(name = "organization_id", nullable = false, length = 32)
    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    @Basic
    @CreationTimestamp
    @Column(name = "created", nullable = false)
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Basic
    @UpdateTimestamp
    @Column(name = "updated", nullable = false)
    public Timestamp getUpdated() {
        return updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        UserOrganizationRelationshipEntity that = (UserOrganizationRelationshipEntity) o;

        if (userId != null ? !userId.equals(that.userId) : that.userId != null) return false;
        if (organizationId != null ? !organizationId.equals(that.organizationId) : that.organizationId != null)
            return false;
        if (created != null ? !created.equals(that.created) : that.created != null) return false;
        if (updated != null ? !updated.equals(that.updated) : that.updated != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = userId != null ? userId.hashCode() : 0;
        result = 31 * result + (organizationId != null ? organizationId.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        result = 31 * result + (updated != null ? updated.hashCode() : 0);
        return result;
    }
}
