package com.sustral.clientapi.data.models;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Mostly autogenerated JPA model.
 *
 * @author Dilanka Dharmasena
 */
@Entity
@Table(name = "users")
public class UserEntity {
    private String id;
    private String email;
    private String name;
    private String auth;
    private Timestamp created;
    private Timestamp updated;
    private Boolean emailVerified;

    public UserEntity() {
        // For the JPA
    }

    public UserEntity(String id, String email, String name, String auth, Boolean emailVerified) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.auth = auth;
        this.emailVerified = emailVerified;
    }

    public UserEntity(String id, String email, String name, String auth, Timestamp created, Timestamp updated, Boolean emailVerified) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.auth = auth;
        this.created = created;
        this.updated = updated;
        this.emailVerified = emailVerified;
    }

    @Id
    @Column(name = "id", nullable = false, length = 32)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Basic
    @Column(name = "email", nullable = false, length = 320)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Basic
    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "auth", nullable = false, length = 60)
    public String getAuth() {
        return auth;
    }

    public void setAuth(String auth) {
        this.auth = auth;
    }

    @Basic
    @Column(name = "created", nullable = false)
    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Basic
    @Column(name = "updated", nullable = false)
    public Timestamp getUpdated() {
        return updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Basic
    @Column(name = "email_verified", nullable = false, columnDefinition = "TINYINT(1)")
    public Boolean getEmailVerified() {
        return emailVerified;
    }

    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        UserEntity that = (UserEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (email != null ? !email.equals(that.email) : that.email != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (auth != null ? !auth.equals(that.auth) : that.auth != null) return false;
        if (created != null ? !created.equals(that.created) : that.created != null) return false;
        if (updated != null ? !updated.equals(that.updated) : that.updated != null) return false;
        if (emailVerified != null ? !emailVerified.equals(that.emailVerified) : that.emailVerified != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (email != null ? email.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (auth != null ? auth.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        result = 31 * result + (updated != null ? updated.hashCode() : 0);
        result = 31 * result + (emailVerified != null ? emailVerified.hashCode() : 0);
        return result;
    }
}
